use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir);

    // Pre-assemble pvm.s (COR24 assembly → machine code) at build time.
    // This avoids running the COR24 assembler in WASM at runtime.
    let pvm_source = std::fs::read_to_string("asm/pvm.s").expect("asm/pvm.s");
    let mut asm = cor24_emulator::Assembler::new();
    let result = asm.assemble(&pvm_source);
    if !result.errors.is_empty() {
        for e in &result.errors {
            eprintln!("pvm.s: {e}");
        }
        panic!("pvm.s assembly failed");
    }
    // Write assembled binary
    std::fs::write(out_path.join("pvm.bin"), &result.bytes).unwrap();
    // Write key label addresses as Rust source
    let labels = [
        (
            "vm_state",
            result.labels.get("vm_state").copied().unwrap_or(0),
        ),
        (
            "eval_stack",
            result.labels.get("eval_stack").copied().unwrap_or(0),
        ),
        (
            "call_stack",
            result.labels.get("call_stack").copied().unwrap_or(0),
        ),
        (
            "code_seg",
            result
                .labels
                .get("code_buf")
                .or(result.labels.get("code_seg"))
                .copied()
                .unwrap_or(0),
        ),
        (
            "vm_loop",
            result.labels.get("vm_loop").copied().unwrap_or(0),
        ),
    ];
    let mut labels_rs = String::from("// Generated by build.rs — do not edit\n");
    labels_rs.push_str("pub const PVM_LABELS: &[(&str, u32)] = &[\n");
    for (name, addr) in &labels {
        labels_rs.push_str(&format!("    (\"{name}\", 0x{addr:06X}),\n"));
    }
    labels_rs.push_str("];\n");
    std::fs::write(out_path.join("pvm_labels.rs"), labels_rs).unwrap();
    println!("cargo:rerun-if-changed=asm/pvm.s");

    // Compile p24p Pascal compiler (C → COR24 assembly → binary) at build time.
    // Uses tc24r CLI to compile p24p C sources, then assembles the output.
    let p24p_src_dir = std::path::Path::new("../p24p/src");
    let tc24r_include = "../../sw-vibe-coding/tc24r/include";
    let tc24r_output = Command::new("tc24r")
        .arg(p24p_src_dir.join("main.c"))
        .arg("-I")
        .arg(tc24r_include)
        .output()
        .expect("tc24r must be installed to compile p24p");
    if !tc24r_output.status.success() {
        let stderr = String::from_utf8_lossy(&tc24r_output.stderr);
        panic!("tc24r compilation of p24p failed:\n{stderr}");
    }
    let p24p_asm = String::from_utf8(tc24r_output.stdout).expect("tc24r produced invalid UTF-8");

    let mut p24p_assembler = cor24_emulator::Assembler::new();
    let p24p_result = p24p_assembler.assemble(&p24p_asm);
    if !p24p_result.errors.is_empty() {
        for e in &p24p_result.errors {
            eprintln!("p24p.s: {e}");
        }
        panic!("p24p assembly failed");
    }
    std::fs::write(out_path.join("p24p.bin"), &p24p_result.bytes).unwrap();
    println!("cargo:rerun-if-changed=../p24p/src/main.c");
    println!("cargo:rerun-if-changed=../p24p/src/parser.c");
    println!("cargo:rerun-if-changed=../p24p/src/parser.h");
    println!("cargo:rerun-if-changed=../p24p/src/lexer.c");
    println!("cargo:rerun-if-changed=../p24p/src/lexer.h");

    // Short git SHA
    let sha = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // Build host
    let host = Command::new("hostname")
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    // ISO timestamp
    let timestamp = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    println!("cargo:rustc-env=BUILD_SHA={sha}");
    println!("cargo:rustc-env=BUILD_HOST={host}");
    println!("cargo:rustc-env=BUILD_TIMESTAMP={timestamp}");
}
